package chong2.see;

/**
 * <p>Title: 软件工程管理环境</p>
 * <p>Description: 为软件研发提供管理数据和任务的平台</p>
 * <p>Copyright: Copyright (c 2004</p>
 * <p>Company: 虫二</p>
 *
 * <p>英语翻译列表
 *
 * @author 玛瑞
 * @version 0.07
 */

public class Res_en extends java.util.ListResourceBundle {

  static final Object[][] contents = new String[][]{
    // by alphabet
    { ":c:e:d-c:e:d:", "End With" },
    { ":c:e:q-c:e:q:", "Equal To" },
    { ":c:g:t-c:g:t:", "Greater Than" },
    { ":c:i:d-c:i:d:", "Include" },
    { ":c:l:s-c:l:s:", "Less Than" },
    { ":c:n:e-c:n:e:", "Not Equal To" },
    { ":c:n:i-c:n:i:", "Not Include" },
    { ":c:s:t-c:s:t:", "Start With" },
    { "abnormity_dealing", "Abnormity Dealing" },
    { "accumulative_count", "Accumulative Count" },
    { "action", "Action" },
    { "actual", "Actual" },
    { "actual_attendee", "Actual Attendee" },
    { "actual_cost", "Actual Cost" },
    { "actual_effort", "Actual Effort" },
    { "actual_end_date", "Actual End Date" },
    { "actual_end_time", "Actual End Time" },
    { "actual_persons", "Actual Person numbers" },
    { "actual_result", "Actual Result" },
    { "actual_size", "Actual Size" },
    { "actual_start_date", "Actual Start Date" },
    { "actual_start_time", "Actual Start Time" },
    { "actual_whole", "Actual(whole)" },
    { "actual_working", "Actual Working" },
    { "add", "Add" },
    { "address", "Address" },
    { "add_all", "Add All" },
    { "advice", "Advice" },
    { "all", "All" },
    { "all_not", "All Not" },
    { "already_exists", "Already Exists" },
    { "analysis", "Analysis" },
    { "answer", "Answer" },
    { "applying", "Applying" },
    { "apply_person", "Apply Person" },
    { "approved", "Approved" },
    { "article", "Article" },
    { "ascending", "Ascending" },
    { "assessor", "Assessor" },
    { "assigned_to", "Assigned to" },
    { "attachment", "Attachment" },
    { "audio", "Audio" },
    { "audit", "Audit" },
    { "audit_following", "The following is corresponding audit records:" },
    { "auditItems", "Audit Items" },
    { "author", "Author" },
    { "authorized", "Authorized" },
    { "authorizer", "Authorizer" },
    { "authorize_time", "Authorize Time" },
    { "auto", "Automatic" },
    { "back", "Back" },
    { "bad_gateway", "Bad Gateway" },
    { "bad_request", "Bad Request" },
    { "batch_modify", "Batch Modify" },
    { "batch_modify_all", "Modify All" },
    { "batch_modify_step1", "Step 1 : Select the data" },
    { "batch_modify_step2", "Step 2 : Input the values" },
    { "bin_code", "Binary Code" },
    { "birthday", "Birthday" },
    { "book", "Book" },
    { "boundary_checking", "Boundary Checking" },
    { "bug", "Bug" },
    { "business", "Business" },
    { "bytes", "Bytes" },
    { "by_data", "By Data" },
    { "by_time", "By Time" },
    { "calculation", "Calculation" },
    { "cancel", "Cancel" },
    { "can_only_include", "Can Only Include" },
    { "can_not_include", "Can Not Include" },
    { "can_not_perform", "Can Not Perform" },
    { "change_content", "Change Content" },
    { "change_request", "Change Request" },
    { "char", "Char" },
    { "charset", "Charset" },
    { "check", "Check" },
    { "check_item", "Check Item" },
    { "check_list", "Check List" },
    { "check_result", "Check Result" },
    { "child", "Child" },
    { "chong2see", "Software Engineering Environment" },
    { "clear", "Clear" },
    { "close", "Close" },
    { "close_window", "Close" },
    { "closed", "Closed" },
    { "code", "Code" },
    { "code_register", "Code Register" },
    { "code_review", "Code Review" },
    { "coding", "Coding" },
    { "color", "Color" },
    { "comment", "Comment" },
    { "commit", "Commit" },
    { "commit_person", "Commit Person" },
    { "commit_time", "Commit Time" },
    { "common_function", "Common Functions" },
    { "component", "Component" },
    { "conclusion", "Conclusion" },
    { "condition", "Condition" },
    { "config", "Config" },
    { "configuration_code", "Configuration Code" },
    { "configuration_management", "Configuration Management" },
    { "configuration_time", "Configuration Time" },
    { "configuration_functionary", "Configuration Functionary" },
    { "conflict", "Conflict" },
    { "configured", "Configured" },
    { "config_warning", "Warning: if this data has already had some records, they might lose when config was changed!" },
    { "contact_way", "Contact Way" },
    { "content", "Content" },
    { "contingency_action", "Contingency Action" },
    { "control_flow", "Control Flow" },
    { "cookie_info", "Your web-browser should permit the cookies of SEE if you want to use SEE." },
    { "copy", "Copy" },
    { "correct", "Correct" },
    { "cost", "Cost" },
    { "count", "Count" },
    { "count_info", "Input values which will be counted, split them by \":-:\". If need system count all values automatically, donot input anything." },
    { "count_matrix", "Count (Matrix)" },
    { "count_show_limit", "The number of data that this chart can only show:" },
    { "creattime", "Creat Time" },
    { "creatuser", "Creat User" },
    { "cross_count", "Cross Count" },
    { "cross_count_matrix", "Cross Count (Matrix)" },
    { "cross_item", "Cross Item" },
    { "cross_matrix_value", "Cross Matrix Value" },
    { "cross_value", "Cross Value" },
    { "current", "Current" },
    { "currenttime", "Current Time" },
    { "currentuser", "Current User" },
    { "current_number", "Current Number" },
    { "current_project", "Current Project" },
    { "current_query_setup", "Current Condition Setup" },
    { "current_show_setup", "Current Show Setup" },
    { "current_statistic_setup", "Current Statistic Setup" },
    { "current_upload_left", "Current Left Upload Space(KB)" },
    { "current_user", "Current User" },
    { "current_value", "Current Value" },
    { "data", "Data" },
    { "database", "Database" },
    { "data_audit", "Data Audit" },
    { "data_audit_types", "Data Audit Types" },
    { "data_checking", "Data Checking" },
    { "data_collection", "Data Collection" },
    { "data_definition", "Data Definition" },
    { "data_manager_guide","Please read <A href=\"manual/en/index.html\" target=_blank>SEE Manual</A> before using SEE."},
    { "data_priviledge", "Data Priviledge" },
    { "data_role", "Data Role" },
    { "data_role_acl", "Data Role Acl" },
    { "data_source", "Data Source" },
    { "data_user_acl", "Data User Acl" },
    { "datalist_style", "Data List Style" },
    { "date", "Date" },
    { "default", "Default" },
    { "defaultColor", "Default Color" },
    { "defaultOrder", "Default Order" },
    { "defaultSort", "Default Sort" },
    { "defaultValue", "Default Value" },
    { "default_encoding", "Default Encoding" },
    { "default_interface_style", "Default Interface Style" },
    { "default_interface_theme", "Default Interface Theme" },
    { "default_page_size", "Default Page Size" },
    { "default_project", "Default Project" },
    { "default_user", "Default User" },
    { "default_upload_size", "Default Upload File Size(KB)" },
    { "default_upload_total", "Default Upload Total(KB)" },
    { "default_value", "Default Value" },
    { "defer", "Defer" },
    { "degree", "Degree" },
    { "denied", "Denied" },
    { "department", "Department" },
    { "description", "Description" },
    { "descending", "Descending" },
    { "design", "Design" },
    { "detail_design", "Detail Design" },
    { "deviation_handling", "Deviation Handling" },
    { "displayName", "Display Name" },
    { "distchart", "Distribution Chart" },
    { "document", "Document" },
    { "document_edit", "Document Edit" },
    { "document_register", "Document Register" },
    { "document_review", "Document Review" },
    { "droplist", "Drop List" },
    { "DBDriver", "Database Driver" },
    { "DBPassword", "Database Password" },
    { "DBUser", "Database User" },
    { "edit", "Edit" },
    { "editControllerType", "Edit Controller Type" },
    { "editWidth", "Edit Width" },
    { "effect_analysis", "Effect Analysis" },
    { "effort", "Effort" },
    { "email", "E-mail" },
    { "en", "English" },
    { "end", "End" },
    { "end_date", "End Date" },
    { "end_time", "End Time" },
    { "end_time_info", "If want to use the latest time, please do not input anything." },
    { "enhancement", "Enhancement" },
    { "error", "Error" },
    { "essentiality", "Essentiality" },
    { "every_page", "Every Page" },
    { "expectation_failed", "Expectation Failed" },
    { "expected_result", "Expected Result" },
    { "explanation", "Explanation" },
    { "export", "Export" },
    { "export_info", "The sorting of this exporting will use the same setup of the current page. If html format will be exported, the color and data-style of the current page will be also used.<BR>If you want to backup data, please select All to Items<BR>To html format, UTF-8 is always used and the setup of charset does not work." },
    { "failure", "Failure" },
    { "failure_to_save", "Failure to Save" },
    { "failure_to_update", "Failure to Update" },
    { "feasibility_research", "Feasibility Research" },
    { "female", "Female" },
    { "field_name_warning", "The following characters and string can not be used in th front of the Identify: 1 2 3 4 5 6 7 8 9 0 - . xml" },
    { "file", "File" },
    { "filesize_info", "File size can not over %%0KB." },
    { "file_info", "If put new file, the current file will be removed. If just remove the current file, please check the Remove selection." },
    { "file_not_found", "File Not Found" },
    { "finish", "Finish" },
    { "fixed", "Fixed" },
    { "float", "Float" },
    { "forbidden", "Forbidden" },
    { "format", "Format" },
    { "form_style", "Form" },
    { "function", "Function" },
    { "gateway_timeout", "Gateway Timeout timeout" },
    { "grant", "Grant" },
    { "group", "Group" },
    { "guest", "guest" },
    { "have_read", "Have Read" },
    { "hello", "Hello! %%0" },
    { "help", "Help" },
    { "hidden", "Hidden" },
    { "hiddenItems", "Hidden Items" },
    { "high", "High" },
    { "histogram", "Histogram" },
    { "histogramcross", "Cross Histogram" },
    { "histogramrate", "Rate Histogram" },
    { "how_long", "How Long" },
    { "http_version_not_supported", "Http Version Not Supported" },
    { "id", "Identify" },
    { "identify", "Identify" },
    { "ignore", "Ignore" },
    { "image", "Image" },
    { "import", "Import" },
    { "importance", "Importance" },
    { "import_info", "Please select a XML file which is in correct format and right structure, or data can not be able to be imported." },
    { "import_override", "To the data with the same keys, override them" },
    { "implemented", "Implemented" },
    { "implementing", "Implementing" },
    { "independant_testing", "Independant Testing" },
    { "ineligible_item", "Ineligible Items" },
    { "inform", "Inform" },
    { "information", "Information" },
    { "init_config", "Init Config" },
    { "input", "Input" },
    { "input_again", "Input Again" },
    { "insert", "Insert" },
    { "int", "Integer" },
    { "interface", "Interface" },
    { "interface_style", "Interface Style" },
    { "interface_theme", "Interface Theme" },
    { "internal_server_error", "Internal Server Error" },
    { "interval", "Interval" },
    { "invalid_data", "Invalid Data" },
    { "invalid_login", "Invalid Login" },
    { "invalid_operation", "Invalid Operation" },
    { "invalidItems", "Invalid Items" },
    { "invalidItems_matrix", "Invalid Matrix Items" },
    { "io_exception", "IO Exception" },
    { "ip", "IP" },
    { "item", "Item" },
    { "items", "Items" },
    { "items_not_defined", "Data items have not been defined." },
    { "job_title", "Job Title" },
    { "jump_to_page", "Jump to Page" },
    { "keep", "Keep" },
    { "keyword", "Keyword" },
    { "keyCanModify", "Key Can Be Modified" },
    { "keys", "Keys" },
    { "lable_style", "Lable" },
    { "language_info", "System is installed in %%0. So it has init accounts and init data in %%0.<BR>Language selection is for showing interface in different languages." },
    { "last_changed_person", "Last Changed Person" },
    { "last_changed_time", "Last Changed Time" },
    { "last_page", "Last Page" },
    { "language", "Language" },
    { "law", "Law" },
    { "length_required", "Length Required" },
    { "level", "Level" },
    { "library_code", "Library Code" },
    { "lines", "Lines" },
    { "link", "Link" },
    { "link_input_error", "Title and value should be input at the same time. Now %%0 is empty." },
    { "list", "List" },
    { "list_data", "List Data" },
    { "location", "Location" },
    { "login", "Login" },
    { "logout", "Logout" },
    { "low", "Low" },
    { "mail_to", "Mail To" },
    { "maintenance", "Maintenance" },
    { "main_data", "Main Data" },
    { "male", "Male" },
    { "manual", "Manual" },
    { "matrix", "Matrix" },
    { "matrixValues", "Matrix Values" },
    { "matrix_data", "Matrix Data" },
    { "matrix_item", "Matrix Item" },
    { "matrix_items", "Matrix Items" },
    { "matrix_info", "One item in each line" },
    { "matrix_value", "Matrix Value" },
    { "max_length", "Max Length" },
    { "medium", "Medium" },
    { "meeting", "Meeting" },
    { "meeting_summary", "Meeting Summary" },
    { "member", "Member" },
    { "message", "Message" },
    { "method_not_allowed", "Method Not Allowed" },
    { "milliseconds", "Milliseconds" },
    { "modify", "Modify" },
    { "module", "Module" },
    { "monthly_meeting", "Monthly Meeting" },
    { "multi", "Multi" },
    { "music", "Music" },
    { "name", "Name" },
    { "new", "New" },
    { "news", "News" },
    { "new_values", "New Values" },
    { "next_page", "Next Page" },
    { "next_step", "Next Step" },
    { "nickname", "Nickname" },
    { "no", "No" },
    { "notice", "Notice" },
    { "no_permission", "No Permission" },
    { "notNullItems", "Not Null Items" },
    { "notNullItems_matrix", "Not Null Matrix Items" },
    { "not_acceptable", "Not Acceptable" },
    { "not_found", "Not Found" },
    { "not_implemented", "Not Implemented" },
    { "not_null", "Not Null" },
    { "not_pass", "Not Pass" },
    { "not_read", "Not Read" },
    { "null", "Null" },
    { "number", "Number" },
    { "object", "Object" },
    { "old_values", "Old Values" },
    { "ok", "Ok" },
    { "one_day", "One Day" },
    { "one_hour", "One Hour" },
    { "one_minute", "One Minute" },
    { "one_month", "One Month" },
    { "one_second", "One Second" },
    { "one_week", "One Week" },
    { "one_year", "One Year" },
    { "open", "Open" },
    { "open_in_new_window", "'Open in New Window" },
    { "operation", "Operation" },
    { "operator", "operator" },
    { "or", "Or" },
    { "order", "Order" },
    { "order_number", "Order Number" },
    { "organization", "Organization" },
    { "others", "Others" },
    { "outline", "Outline" },
    { "output", "Output" },
    { "over_limit", "Over Limit" },
    { "override", "Override" },
    { "pages", "Pages" },
    { "page_size", "Page Size" },
    { "pass", "Pass" },
    { "participator", "Participator" },
    { "part_pass", "Part Passed" },
    { "password", "Password" },
    { "password_info", "If not modify password, do not input anything." },
    { "payment_required", "Payment Required" },
    { "performance", "Performance" },
    { "performing", "Performing" },
    { "person", "Person" },
    { "person_day", "Person Day" },
    { "person_hour", "Person Hour" },
    { "person_month", "Person Month" },
    { "personal_message", "Personal Message" },
    { "phone", "Phone" },
    { "piechart", "Pie Chart" },
    { "piecross", "Cross Pie Chart" },
    { "plan", "Plan" },
    { "plan_attendee", "Plan Attendee" },
    { "plan_cost", "Plan Cost" },
    { "plan_date", "Plan Date" },
    { "plan_effort", "Plan Effort" },
    { "plan_end_date", "Plan End Date" },
    { "plan_end_time", "Plan End Time" },
    { "plan_persons", "Plan Person numbers" },
    { "plan_start_date", "Plan Start Date" },
    { "plan_start_time", "Plan Start Time" },
    { "plan_whole", "Plan(whole)" },
    { "plan_working", "Plan Working" },
    { "please_select", "Please Select" },
    { "pm_query_info", "A message is \"read\" only after the receiver open it." },
    { "pm_remove_info", "You can only remove what you have received." },
    { "pm_size_info", "You have %%0 new messages." },
    { "precondition_failed", "Precondition Failed" },
    { "preliminary_design", "Preliminary Design" },
    { "preserve", "Preserve" },
    { "priority", "Priority" },
    { "priviledge", "Priviledge" },
    { "probability", "Probability" },
    { "problem_report", "Problem Report" },
    { "project", "Project" },
    { "project_manager", "Project Manager" },
    { "project_management", "Project Management" },
    { "project_planning", "Project Planning" },
    { "project_role", "Project Roles" },
    { "project_size", "Project Size" },
    { "project_size_tracking", "Project Size Tracking" },
    { "project_stage", "Project Stages" },
    { "project_task", "Project Tasks" },
    { "project_tracking", "Project Tracking" },
    { "proxy_authentication_required", "Proxy Authentication Required" },
    { "public", "Public" },
    { "public_data", "Public Data" },
    { "quality", "Quality" },
    { "quality_management", "Quality Management" },
    { "query", "Query" },
    { "queryItems", "Query Items" },
    { "query_baseinfo", "The following are current base conditions. Whatever Your new conditions are, they will be checked at first." },
    { "query_info", "Lines in the following tables have the relationship \"And\", and these tables have the relationship \"Or\"." },
    { "query_setup", "Condition Setup" },
    { "query_setup_info", "The following conditions have the relationship \"And\".<BR>When use the operator \"Greater Than\" or \"Less Than \", data will be compared according to their types, such as date, time, integer, and string." },
    { "question", "Question" },
    { "radio", "Radio" },
    { "rate", "Rate" },
    { "readonly", "Readonly" },
    { "reason", "Reason" },
    { "receive", "Receive" },
    { "receiver", "Receiver" },
    { "recorder", "Recorder" },
    { "ref_multi", "Refer_Multi" },
    { "ref_solo", "Refer_Solo" },
    { "register_person", "Register Person" },
    { "register_time", "Register Time" },
    { "relative_code", "Relative Codes" },
    { "relative_doc", "Relative Documents" },
    { "relative_person", "Relative Persons" },
    { "remark", "Remark" },
    { "remember_me", "Remember Me" },
    { "remove", "Remove" },
    { "remove_all", "Remove All" },
    { "remove_failure_des", "Remove Failure des" },
    { "remove_selected", "Remove Selected" },
    { "reporter", "Reporter" },
    { "report_date", "Report Date" },
    { "requested_range_not_satisfiable", "Requested Range Not Satisfiable" },
    { "request_entity_too_large", "Request Entity Too Large" },
    { "request_timeout", "Request Timeout" },
    { "request_uri_too_long", "Request Uri Too Long" },
    { "requirement", "Requirement" },
    { "requirement_analysis", "Requirement Analysis" },
    { "response_speed", "Response Speed" },
    { "review", "Review" },
    { "reviewed", "Reviewed" },
    { "review_date", "Review Date" },
    { "review_persons", "Review Persons" },
    { "review_time", "Review Time" },
    { "revision", "Revision" },
    { "reset", "Reset" },
    { "result", "Result" },
    { "risk_analysis", "Risk Analysis" },
    { "risk_item", "Risk Item" },
    { "robust", "Robust" },
    { "role", "Role" },
    { "role_definition", "Role Defination" },
    { "save", "Save" },
    { "save_as_new", "Save As New" },
    { "save_failure_des",
    "Data should not be empty.<BR>The red fields must be unique.<BR>The blue fields should not be blank." },
    { "scope", "Scope" },
    { "secrecy", "Secrecy" },
    { "secret", "Secret" },
    { "security", "Security" },
    { "see_author", "Mara Ren" },
    { "see_speed_info", "This testing is only for the time-consuming about reading, sorting, and writing with XML files. When using functions of SEE, more time will be consumed for constructing page elements." },
    { "see_speed_testing", "Speed Testing" },
    { "select", "Select" },
    { "select_all", "Select All" },
    { "select_none", "Select None" },
    { "select_query_setup", "Use or maintain one of the following saved query-setups:" },
    { "select_show_setup", "Use or maintain one of the following saved show-setups:" },
    { "self", "Self" },
    { "send", "Send" },
    { "sender", "Sender" },
    { "send_mail", "Send Mail" },
    { "sent", "Sent" },
    { "sent_time", "Sent Time" },
    { "service_unavailable", "Service Unavailable" },
    { "setup", "Setup" },
    { "set_null", "Set Null" },
    { "set_query_setup", "Set directly or maintain the query-setups" },
    { "set_show_setup", "Set directly or maintain the show-setups" },
    { "set_statistic_setup", "Set directly or maintain the statistic-setups" },
    { "severity", "Severity" },
    { "sex", "Sex" },
    { "share_resource", "Share Resource" },
    { "should_not_null", "Should not null" },
    { "show", "Show" },
    { "showControllerType", "Show Controller Type" },
    { "showItems", "Show Items" },
    { "show_record", "Show Record" },
    { "show_setup", "Show Setup" },
    { "show_value", "Show Value" },
    { "size", "Size" },
    { "software", "Software" },
    { "software_implementation", "Software Implementation" },
    { "software_requirement", "Software Requirement" },
    { "solo", "Solo" },
    { "sort", "Sort" },
    { "sort_info", "Click any item name in the table, data will be sorted by that item. Click again, sort them in different direction." },
    { "source", "Source" },
    { "src_code", "Source Code" },
    { "staff_number", "Staff Number" },
    { "start", "Start" },
    { "start_date", "Start Date" },
    { "start_time", "Start Time" },
    { "start_time_info", "If want to use the earliest time, please do not input anything." },
    { "statistic", "Statistic" },
    { "statistic_setup", "Statistic Setup" },
    { "status", "Status" },
    { "steps", "Steps" },
    { "string", "String" },
    { "structure", "Structure" },
    { "style", "Style" },
    { "style_default", "Default Style" },
    { "style_flowers", "Beautiful Flowers" },
    { "submit", "Submit" },
    { "successful", "Successful" },
    { "supervisor", "Supervisor" },
    { "sure_batch_modify_all", "Sure to modify all?" },
    { "sure_batch_modify_selected", "Sure to modify the selected?" },
    { "sure_remove", "Sure to remove?" },
    { "sure_remove_all", "Sure to remove all?" },
    { "sure_remove_selected", "Sure to remove the selected?" },
    { "system", "System" },
    { "system_management", "System Management" },
    { "system_role", "System Role" },
    { "system_role_acl", "System Role Acl" },
    { "system_user", "System User" },
    { "superseer", "superseer" },
    { "table", "Table" },
    { "table_style", "Table" },
    { "technical_supporting", "Technical Supporting" },
    { "technique", "Technique" },
    { "tested", "Tested" },
    { "tester", "Tester" },
    { "testing", "Testing" },
    { "testing_code", "Testing Code" },
    { "testing_data", "Testing Data" },
    { "testing_design", "Testing Design" },
    { "testing_report", "Testing Report" },
    { "testing_requirement", "Testing Requirement" },
    { "testing_result", "Testing Result" },
    { "testing_procedure", "Testing Procedure" },
    { "testing_time", "Testing Time" },
    { "text", "Text" },
    { "textarea", "Textarea" },
    { "theme", "Theme" },
    { "theme_default", "Default Theme" },
    { "time", "Time" },
    { "time_number", "Time Number" },
    { "title", "Title" },
    { "top_secret", "Top-secret" },
    { "total_count", "Total Count" },
    { "tmp_file_warning", "This is a temporary file. System will delete it in %%0 minutes. So please open or save it in time." },
    { "training", "Training" },
    { "tree", "Tree" },
    { "trend", "Trend" },
    { "trend_matrix", "Trend (Matrix)" },
    { "trimmer", "Trimmer" },
    { "twice_input_different", "different in two input" },
    { "type", "Type" },
    { "yes", "Yes" },
    { "update", "Update" },
    { "upload_management", "Upload Management" },
    { "upload_size_over", "The upload file size is over the limit." },
    { "upload_total_over", "The upload space is not enough, please inform the administrator." },
    { "unauthorized", "Unauthorized" },
    { "unit", "Unit" },
    { "unitage", "Unit" },
    { "unsupported_media_type", "Unsupported Media Type" },
    { "use", "Use" },
    { "user", "User" },
    { "user_feedback", "User Feedback" },
    { "user_manual", "User Manual" },
    { "user_model", "User Model" },
    { "use_guide", "Use Guide" },
    { "valid", "Valid" },
    { "validated", "Validated" },
    { "value", "Value" },
    { "valueConstraint", "Value Constraint" },
    { "valueConstraintType", "Value Constraint Type" },
    { "valueTranslated", "Value Translated" },
    { "version", "Version" },
    { "very_high", "Very High" },
    { "very_low", "Very Low" },
    { "video ", "Video" },
    { "weekly_meeting", "Weekly Meeting" },
    { "weekly_report", "Weekly Report" },
    { "welcome", "Welcome" },
    { "when", "When" },
    { "where", "Where" },
    { "who", "Who" },
    { "words", "Words" },
    { "working_log", "Working Log" },
    { "yuan", "$" },
    { "zh_CN", "Simplified Chinese" },
    { "zh_TW", "Traditional Chinese" },
    { "SEE-count-other", "Other" },
    { "SEE-count-null", "Null" },
    { "SEE_matrix_value", "Matrix Value" }

  };

  public Object[][] getContents() {
    return contents;
  }
}